// @ts-nocheck
const RE_DATA = (() => {
  const TYPES = {
    house:     { emoji:'🏠', label:'Nhà',              incomeRate:0.0008 },
    office:    { emoji:'🏢', label:'Văn Phòng',        incomeRate:0.0012 },
    hotel:     { emoji:'🏨', label:'Khách Sạn',        incomeRate:0.0015 },
    apartment: { emoji:'🏬', label:'Chung Cư',         incomeRate:0.0010 },
    warehouse: { emoji:'🏭', label:'Nhà Xưởng',        incomeRate:0.0009 },
    villa:     { emoji:'🏰', label:'Biệt Thự/Lâu Đài', incomeRate:0.0006 },
    island:    { emoji:'🏝️', label:'Đảo Tư Nhân',      incomeRate:0.0005 },
  };

  const RENOVATION = [
    null,
    { level:1, name:'Sơn',           emoji:'🎨', costPct:0.02, incomeBuff:0.10 },
    { level:2, name:'Trang Trí',     emoji:'🖼️', costPct:0.05, incomeBuff:0.20 },
    { level:3, name:'Nội Thất',      emoji:'🛋️', costPct:0.10, incomeBuff:0.35 },
    { level:4, name:'Kết Cấu',       emoji:'🏗️', costPct:0.15, incomeBuff:0.55 },
    { level:5, name:'Bố Trí Phòng',  emoji:'🚪', costPct:0.20, incomeBuff:0.80 },
    { level:6, name:'Smart House',   emoji:'🤖', costPct:0.30, incomeBuff:1.20 },
  ];

  const P = [
    // NHÀ
    {id:'h01',type:'house',    name:'Nhà Phố Hà Nội',       city:'Hà Nội',      country:'🇻🇳',price:50_000},
    {id:'h02',type:'house',    name:'Nhà Phố TP.HCM',       city:'TP.HCM',      country:'🇻🇳',price:80_000},
    {id:'h03',type:'house',    name:'Nhà Liền Kề Đà Nẵng',  city:'Đà Nẵng',     country:'🇻🇳',price:120_000},
    {id:'h04',type:'house',    name:'Townhouse Bangkok',     city:'Bangkok',     country:'🇹🇭',price:180_000},
    {id:'h05',type:'house',    name:'Terraced House London', city:'London',      country:'🇬🇧',price:450_000},
    {id:'h06',type:'house',    name:'Semi-Detached Paris',   city:'Paris',       country:'🇫🇷',price:520_000},
    {id:'h07',type:'house',    name:'Brownstone New York',   city:'New York',    country:'🇺🇸',price:750_000},
    {id:'h08',type:'house',    name:'Bungalow Sydney',       city:'Sydney',      country:'🇦🇺',price:820_000},
    {id:'h09',type:'house',    name:'Villa Nice',            city:'Nice',        country:'🇫🇷',price:1_200_000},
    {id:'h10',type:'house',    name:'Chalet Zurich',         city:'Zurich',      country:'🇨🇭',price:1_500_000},
    {id:'h11',type:'house',    name:'Mansion Los Angeles',   city:'Los Angeles', country:'🇺🇸',price:2_000_000},
    {id:'h12',type:'house',    name:'Penthouse Singapore',   city:'Singapore',   country:'🇸🇬',price:2_500_000},
    {id:'h13',type:'house',    name:'Townhouse Mayfair',     city:'London',      country:'🇬🇧',price:3_000_000},
    {id:'h14',type:'house',    name:'Villa Santorini',       city:'Santorini',   country:'🇬🇷',price:3_500_000},
    {id:'h15',type:'house',    name:'Mansion Beverly Hills', city:'Beverly Hills',country:'🇺🇸',price:5_000_000},
    {id:'h16',type:'house',    name:'Villa Tuscany',         city:'Tuscany',     country:'🇮🇹',price:6_000_000},
    {id:'h17',type:'house',    name:'Upper East Side NYC',   city:'New York',    country:'🇺🇸',price:8_000_000},
    {id:'h18',type:'house',    name:'Mansion Knightsbridge', city:'London',      country:'🇬🇧',price:10_000_000},
    {id:'h19',type:'house',    name:'Villa Cap Ferrat',      city:'French Riviera',country:'🇫🇷',price:15_000_000},
    {id:'h20',type:'house',    name:'Palazzo Venice',        city:'Venice',      country:'🇮🇹',price:20_000_000},
    {id:'h21',type:'house',    name:'Estate Hamptons',       city:'Hamptons',    country:'🇺🇸',price:30_000_000},
    {id:'h22',type:'house',    name:'Villa Portofino',       city:'Portofino',   country:'🇮🇹',price:40_000_000},
    {id:'h23',type:'house',    name:'Mansion Monte Carlo',   city:'Monaco',      country:'🇲🇨',price:60_000_000},
    {id:'h24',type:'house',    name:'Estate Palm Beach',     city:'Palm Beach',  country:'🇺🇸',price:80_000_000},
    {id:'h25',type:'house',    name:'Villa Malibu Clifftop', city:'Malibu',      country:'🇺🇸',price:120_000_000},
    // VĂN PHÒNG
    {id:'o01',type:'office',   name:'VP Hoàn Kiếm',          city:'Hà Nội',      country:'🇻🇳',price:100_000},
    {id:'o02',type:'office',   name:'Office Quận 1',         city:'TP.HCM',      country:'🇻🇳',price:150_000},
    {id:'o03',type:'office',   name:'Office Bangkok CBD',    city:'Bangkok',     country:'🇹🇭',price:250_000},
    {id:'o04',type:'office',   name:'Office Canary Wharf',   city:'London',      country:'🇬🇧',price:800_000},
    {id:'o05',type:'office',   name:'Office La Defense',     city:'Paris',       country:'🇫🇷',price:900_000},
    {id:'o06',type:'office',   name:'Office Midtown NYC',    city:'New York',    country:'🇺🇸',price:1_500_000},
    {id:'o07',type:'office',   name:'Office Roppongi Hills', city:'Tokyo',       country:'🇯🇵',price:1_800_000},
    {id:'o08',type:'office',   name:'Office Marina Bay',     city:'Singapore',   country:'🇸🇬',price:2_000_000},
    {id:'o09',type:'office',   name:'Office Dubai DIFC',     city:'Dubai',       country:'🇦🇪',price:3_500_000},
    {id:'o10',type:'office',   name:'Office Wall Street',    city:'New York',    country:'🇺🇸',price:6_000_000},
    {id:'o11',type:'office',   name:'Skyscraper HK',         city:'Hong Kong',   country:'🇭🇰',price:8_000_000},
    {id:'o12',type:'office',   name:'Tower Beijing CBD',     city:'Beijing',     country:'🇨🇳',price:10_000_000},
    {id:'o13',type:'office',   name:'Burj Khalifa Suite',    city:'Dubai',       country:'🇦🇪',price:20_000_000},
    {id:'o14',type:'office',   name:'One Canada Square',     city:'London',      country:'🇬🇧',price:30_000_000},
    {id:'o15',type:'office',   name:'Empire State Floors',   city:'New York',    country:'🇺🇸',price:50_000_000},
    {id:'o16',type:'office',   name:'Shanghai Tower Floor',  city:'Shanghai',    country:'🇨🇳',price:35_000_000},
    {id:'o17',type:'office',   name:'Skyscraper HQ NYC',     city:'New York',    country:'🇺🇸',price:100_000_000},
    // KHÁCH SẠN
    {id:'k01',type:'hotel',    name:'Hotel Hoan Kiem',       city:'Hà Nội',      country:'🇻🇳',price:200_000},
    {id:'k02',type:'hotel',    name:'Resort Phu Quoc',       city:'Phú Quốc',    country:'🇻🇳',price:500_000},
    {id:'k03',type:'hotel',    name:'Hotel Bali Kuta',       city:'Bali',        country:'🇮🇩',price:800_000},
    {id:'k04',type:'hotel',    name:'Hotel Ibiza',           city:'Ibiza',       country:'🇪🇸',price:2_000_000},
    {id:'k05',type:'hotel',    name:'Hotel Amalfi Coast',    city:'Amalfi',      country:'🇮🇹',price:3_000_000},
    {id:'k06',type:'hotel',    name:'Resort Maldives',       city:'Maldives',    country:'🇲🇻',price:5_000_000},
    {id:'k07',type:'hotel',    name:'Resort Bora Bora',      city:'Bora Bora',   country:'🇵🇫',price:10_000_000},
    {id:'k08',type:'hotel',    name:'Hotel Dubai Marina',    city:'Dubai',       country:'🇦🇪',price:12_000_000},
    {id:'k09',type:'hotel',    name:'Resort Seychelles',     city:'Seychelles',  country:'🇸🇨',price:15_000_000},
    {id:'k10',type:'hotel',    name:'Ritz Carlton London',   city:'London',      country:'🇬🇧',price:20_000_000},
    {id:'k11',type:'hotel',    name:'Park Hyatt Tokyo',      city:'Tokyo',       country:'🇯🇵',price:25_000_000},
    {id:'k12',type:'hotel',    name:'Aman Venice',           city:'Venice',      country:'🇮🇹',price:30_000_000},
    {id:'k13',type:'hotel',    name:'Burj Al Arab Dubai',    city:'Dubai',       country:'🇦🇪',price:50_000_000},
    {id:'k14',type:'hotel',    name:'The Plaza New York',    city:'New York',    country:'🇺🇸',price:60_000_000},
    {id:'k15',type:'hotel',    name:'Hotel de Paris Monaco', city:'Monaco',      country:'🇲🇨',price:80_000_000},
    {id:'k16',type:'hotel',    name:'Hotel Ritz Paris',      city:'Paris',       country:'🇫🇷',price:90_000_000},
    {id:'k17',type:'hotel',    name:'Waldorf Astoria NYC',   city:'New York',    country:'🇺🇸',price:120_000_000},
    {id:'k18',type:'hotel',    name:'Hotel Chain Empire',    city:'Global',      country:'🌍',price:500_000_000},
    // CHUNG CU
    {id:'c01',type:'apartment',name:'Chung Cu Ha Dong',      city:'Hà Nội',      country:'🇻🇳',price:60_000},
    {id:'c02',type:'apartment',name:'Can Ho Binh Thanh',     city:'TP.HCM',      country:'🇻🇳',price:90_000},
    {id:'c03',type:'apartment',name:'Condo Bangkok',         city:'Bangkok',     country:'🇹🇭',price:150_000},
    {id:'c04',type:'apartment',name:'Flat East London',      city:'London',      country:'🇬🇧',price:350_000},
    {id:'c05',type:'apartment',name:'Studio Paris',          city:'Paris',       country:'🇫🇷',price:400_000},
    {id:'c06',type:'apartment',name:'Condo Manhattan',       city:'New York',    country:'🇺🇸',price:700_000},
    {id:'c07',type:'apartment',name:'Apartment Shibuya',     city:'Tokyo',       country:'🇯🇵',price:600_000},
    {id:'c08',type:'apartment',name:'Condo Orchard Road',    city:'Singapore',   country:'🇸🇬',price:900_000},
    {id:'c09',type:'apartment',name:'Flat Kensington',       city:'London',      country:'🇬🇧',price:1_200_000},
    {id:'c10',type:'apartment',name:'Condo Gangnam',         city:'Seoul',       country:'🇰🇷',price:1_000_000},
    {id:'c11',type:'apartment',name:'Penthouse Miami',       city:'Miami',       country:'🇺🇸',price:2_000_000},
    {id:'c12',type:'apartment',name:'Penthouse Dubai',       city:'Dubai',       country:'🇦🇪',price:3_000_000},
    {id:'c13',type:'apartment',name:'Penthouse Hong Kong',   city:'Hong Kong',   country:'🇭🇰',price:4_000_000},
    {id:'c14',type:'apartment',name:'Sky Villa Singapore',   city:'Singapore',   country:'🇸🇬',price:5_000_000},
    {id:'c15',type:'apartment',name:'Penthouse Manhattan',   city:'New York',    country:'🇺🇸',price:8_000_000},
    {id:'c16',type:'apartment',name:'Penthouse Mayfair',     city:'London',      country:'🇬🇧',price:10_000_000},
    {id:'c17',type:'apartment',name:'Triplex Paris 8eme',    city:'Paris',       country:'🇫🇷',price:12_000_000},
    {id:'c18',type:'apartment',name:'Sky Penthouse Monaco',  city:'Monaco',      country:'🇲🇨',price:20_000_000},
    {id:'c19',type:'apartment',name:'Penthouse One57 NYC',   city:'New York',    country:'🇺🇸',price:35_000_000},
    {id:'c20',type:'apartment',name:'432 Park Ave Penthouse',city:'New York',    country:'🇺🇸',price:50_000_000},
    {id:'c21',type:'apartment',name:'The Shard Penthouse',   city:'London',      country:'🇬🇧',price:30_000_000},
    {id:'c22',type:'apartment',name:'Penthouse Burj Khalifa',city:'Dubai',       country:'🇦🇪',price:15_000_000},
    // NHA XUONG
    {id:'w01',type:'warehouse',name:'Kho Bac Ninh',          city:'Bắc Ninh',    country:'🇻🇳',price:80_000},
    {id:'w02',type:'warehouse',name:'Nha Xuong Binh Duong',  city:'Bình Dương',  country:'🇻🇳',price:150_000},
    {id:'w03',type:'warehouse',name:'Factory Rayong',        city:'Rayong',      country:'🇹🇭',price:300_000},
    {id:'w04',type:'warehouse',name:'Warehouse Rotterdam',   city:'Rotterdam',   country:'🇳🇱',price:600_000},
    {id:'w05',type:'warehouse',name:'Factory Detroit',       city:'Detroit',     country:'🇺🇸',price:700_000},
    {id:'w06',type:'warehouse',name:'Industrial Frankfurt',  city:'Frankfurt',   country:'🇩🇪',price:1_000_000},
    {id:'w07',type:'warehouse',name:'Tech Factory Shenzhen', city:'Shenzhen',    country:'🇨🇳',price:1_200_000},
    {id:'w08',type:'warehouse',name:'Auto Factory Munich',   city:'Munich',      country:'🇩🇪',price:2_000_000},
    {id:'w09',type:'warehouse',name:'Logistics Dallas',      city:'Dallas',      country:'🇺🇸',price:2_500_000},
    {id:'w10',type:'warehouse',name:'Auto Plant Stuttgart',  city:'Stuttgart',   country:'🇩🇪',price:3_000_000},
    {id:'w11',type:'warehouse',name:'Chip Factory Taipei',   city:'Taipei',      country:'🇹🇼',price:5_000_000},
    {id:'w12',type:'warehouse',name:'Data Center Virginia',  city:'Virginia',    country:'🇺🇸',price:6_000_000},
    {id:'w13',type:'warehouse',name:'Tesla Gigafactory',     city:'Nevada',      country:'🇺🇸',price:10_000_000},
    {id:'w14',type:'warehouse',name:'Apple Campus',          city:'Cupertino',   country:'🇺🇸',price:15_000_000},
    {id:'w15',type:'warehouse',name:'TSMC Fab Hsinchu',      city:'Hsinchu',     country:'🇹🇼',price:20_000_000},
    {id:'w16',type:'warehouse',name:'Oil Refinery Houston',  city:'Houston',     country:'🇺🇸',price:25_000_000},
    {id:'w17',type:'warehouse',name:'Port Terminal Shanghai',city:'Shanghai',    country:'🇨🇳',price:30_000_000},
    {id:'w18',type:'warehouse',name:'Space Launch Complex',  city:'Cape Canaveral',country:'🇺🇸',price:50_000_000},
    {id:'w19',type:'warehouse',name:'Nuclear Plant Complex', city:'France',      country:'🇫🇷',price:80_000_000},
    {id:'w20',type:'warehouse',name:'Mega Factory Complex',  city:'Global',      country:'🌍',price:200_000_000},
    // BIET THU / LAU DAI
    {id:'v01',type:'villa',    name:'Biet Thu Vinhomes',     city:'Hà Nội',      country:'🇻🇳',price:500_000},
    {id:'v02',type:'villa',    name:'Villa Da Lat',          city:'Đà Lạt',      country:'🇻🇳',price:800_000},
    {id:'v03',type:'villa',    name:'Pool Villa Samui',      city:'Koh Samui',   country:'🇹🇭',price:1_500_000},
    {id:'v04',type:'villa',    name:'Villa Ubud Bali',       city:'Ubud',        country:'🇮🇩',price:2_000_000},
    {id:'v05',type:'villa',    name:'Finca Mallorca',        city:'Mallorca',    country:'🇪🇸',price:3_000_000},
    {id:'v06',type:'villa',    name:'Villa Lake Geneva',     city:'Geneva',      country:'🇨🇭',price:5_000_000},
    {id:'v07',type:'villa',    name:'Villa Cote d Azur',     city:'Cannes',      country:'🇫🇷',price:8_000_000},
    {id:'v08',type:'villa',    name:'Chateau Loire Valley',  city:'Loire',       country:'🇫🇷',price:12_000_000},
    {id:'v09',type:'villa',    name:'Castle Scotland',       city:'Edinburgh',   country:'🇬🇧',price:10_000_000},
    {id:'v10',type:'villa',    name:'Schloss Bavaria',       city:'Bavaria',     country:'🇩🇪',price:15_000_000},
    {id:'v11',type:'villa',    name:'Villa Monaco',          city:'Monaco',      country:'🇲🇨',price:25_000_000},
    {id:'v12',type:'villa',    name:'Royal Villa Capri',     city:'Capri',       country:'🇮🇹',price:30_000_000},
    {id:'v13',type:'villa',    name:'Chateau Bordeaux',      city:'Bordeaux',    country:'🇫🇷',price:35_000_000},
    {id:'v14',type:'villa',    name:'Hearst Castle',         city:'California',  country:'🇺🇸',price:100_000_000},
    {id:'v15',type:'villa',    name:'Biltmore Estate',       city:'N. Carolina', country:'🇺🇸',price:150_000_000},
    {id:'v16',type:'villa',    name:'Windsor Castle 🏰',     city:'Windsor',     country:'🇬🇧',price:1_000_000_000},
    {id:'v17',type:'villa',    name:'Neuschwanstein 🏰',     city:'Bavaria',     country:'🇩🇪',price:3_000_000_000},
    {id:'v18',type:'villa',    name:'Buckingham Palace 🏰',  city:'London',      country:'🇬🇧',price:5_000_000_000},
    {id:'v19',type:'villa',    name:'Versailles Palace 🏰',  city:'Paris',       country:'🇫🇷',price:10_000_000_000},
    {id:'v20',type:'villa',    name:'Forbidden City 🏰',     city:'Beijing',     country:'🇨🇳',price:8_000_000_000},
    // DAO TU NHAN
    {id:'i01',type:'island',   name:'Dao nho Ha Long',       city:'Quảng Ninh',  country:'🇻🇳',price:1_000_000},
    {id:'i02',type:'island',   name:'Island Phuket',         city:'Phuket',      country:'🇹🇭',price:2_000_000},
    {id:'i03',type:'island',   name:'Private Island Bali',   city:'Bali',        country:'🇮🇩',price:5_000_000},
    {id:'i04',type:'island',   name:'Island Seychelles',     city:'Seychelles',  country:'🇸🇨',price:8_000_000},
    {id:'i05',type:'island',   name:'Island Maldives',       city:'Maldives',    country:'🇲🇻',price:10_000_000},
    {id:'i06',type:'island',   name:'Island Bahamas',        city:'Bahamas',     country:'🇧🇸',price:12_000_000},
    {id:'i07',type:'island',   name:'Island Fiji',           city:'Fiji',        country:'🇫🇯',price:18_000_000},
    {id:'i08',type:'island',   name:'Island French Poly',    city:'Tahiti',      country:'🇵🇫',price:25_000_000},
    {id:'i09',type:'island',   name:'Island Sardinia',       city:'Sardinia',    country:'🇮🇹',price:30_000_000},
    {id:'i10',type:'island',   name:'Island New Zealand',    city:'Bay of Islands',country:'🇳🇿',price:40_000_000},
    {id:'i11',type:'island',   name:'Island Caribbean',      city:'Caribbean',   country:'🌊',price:60_000_000},
    {id:'i12',type:'island',   name:'Necker Island BVI',     city:'BVI',         country:'🇻🇬',price:100_000_000},
    {id:'i13',type:'island',   name:'Lanai Hawaii',          city:'Hawaii',      country:'🇺🇸',price:300_000_000},
    {id:'i14',type:'island',   name:'Skorpios Greece',       city:'Lefkada',     country:'🇬🇷',price:200_000_000},
    {id:'i15',type:'island',   name:'Manhattan Island 🗽',    city:'New York',    country:'🇺🇸',price:1_000_000_000_000},
  ];

  P.sort((a, b) => a.price - b.price);
  return { TYPES, RENOVATION, PROPERTIES: P };
})();
